language: java
jdk:
- oraclejdk8
before_install:
openssl aes-256-cbc -K $encrypted_a89e6dcd6038_key -iv $encrypted_a89e6dcd6038_iv -in src/main/resource/application.properties.enc -out src/main/resource/application.properties -d